In [1]:
from keras.models import load_model
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
from skimage.transform import resize
import os

C:\ProgramData\Anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

WARNING:tensorflow:From C:\Users\Laura Valbuena\AppData\Roaming\Python\Python39\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

# Cargar el modelo

In [2]:
model = load_model("leucemia_mnist.h5")

WARNING:tensorflow:From C:\Users\Laura Valbuena\AppData\Roaming\Python\Python39\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

WARNING:tensorflow:From C:\Users\Laura Valbuena\AppData\Roaming\Python\Python39\site-packages\keras\src\layers\pooling\max_pooling2d.py:161: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

# Prediccion de una nueva imagen

In [3]:
images=[]
# AQUI ESPECIFICAMOS UNAS IMAGENES
dirname = os.path.join(os.getcwd(), 'datos/Val/validation_data')
filenames = [dirname+'/1.bmp']
print (filenames)

['C:\\Users\\Laura Valbuena\\Documents\\Proyecto\\M1000-IA--LLA-\\datos/Val/validation_data/1.bmp']

In [4]:
for filepath in filenames:
    image = plt.imread(filepath,0)
    image_resized = resize(image, (257, 257),anti_aliasing=True,clip=False,preserve_range=True)
    images.append(image_resized)

In [5]:
X = np.array(images, dtype=np.uint8) #convierto de lista a numpy
test_X = X.astype('float32')
test_X = test_X / 257.

In [6]:
predicted_classes = model.predict(test_X)
estado=['Malignant','Benign']
print(predicted_classes)

1/1 [==============================] - 0s 288ms/step
[[0.8782082  0.12179184]]

In [7]:
for i, img_tagged in enumerate(predicted_classes):
    predict = estado[img_tagged.tolist().index(max(img_tagged))]
    print(filenames[i]+ " .... "+predict)

C:\Users\Laura Valbuena\Documents\Proyecto\M1000-IA--LLA-\datos/Val/validation_data/1.bmp .... Malignant

# Prediccion de varias imagenes de validación

Se crea el dataframe donde se guardaran las predicciones de cada imagen para luego comparar con el diagnostico real de la imagen

In [8]:
df_predicted = pd.DataFrame()

# creamos las columnas
df_predicted['Filename'] = None
df_predicted['Prediccion'] = None

1. Recorremos el directorio que contiene 1867 imagenes, se realiza el reajuste del tamaño, se realiza la predicción y se guarda el resultado por cada imagen

2. El modelo tiene como respuesta ***Malignant** o **Benign**, sin embargo como el dataframe que tiene el diagnostico correcto, el dagnostico lo tiene en valores de 1 y 0 donde:

* 1 - Malignant

* 0 - Benign

Dentro de este recorrido hacemos un casteo para que convierta la salida del modelo en 1 o 0, para luego validar el resultado correcto, con el predicho

In [9]:
dirname = os.path.join(os.getcwd(), 'datos')
imgpath = dirname + os.sep 

images = []
directories = []
dircount = []
prevRoot=''
cant=0

print("leyendo imagenes de ",imgpath)

for root, dirnames, filenames in os.walk(imgpath):
    head_tail  = os.path.split(root)
    if head_tail[1] == 'validation_data':
        for filename in filenames:
            if re.search("\.(jpg|jpeg|png|bmp|tif)$", filename):
                images = []
                cant=cant+1
                filepath = os.path.join(root, filename)
                image = plt.imread(filepath)
                image = plt.imread(filepath,0)
                image_resized = resize(image, (257, 257),anti_aliasing=True,clip=False,preserve_range=True)
                images.append(image_resized)
                X = np.array(images, dtype=np.uint8) #convierto de lista a numpy
                #images.clear()
                test_X = X.astype('float32')
                test_X = test_X / 257.
                predicted_classes = model.predict(test_X)
                for i, img_tagged in enumerate(predicted_classes):
                    predict = estado[img_tagged.tolist().index(max(img_tagged))] 
                    if predict == 'Malignant':
                        predict = 1
                    else :
                        predict = 0
                    df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)
                    print("Validando: "+ filename+" -> Prediccion: "+str(predict))
                b = "Leyendo..."+ str(cant)
                print (b, end="\r")
                if prevRoot !=root:
                    print(root, cant)
                    prevRoot=root
                    directories.append(root)
                    dircount.append(cant)
                    cant=0
dircount.append(cant)

dircount = dircount[1:]
dircount[0]=dircount[0]+1
print('Directorios leidos:',len(directories))
print("Imagenes en cada directorio", dircount)
print('suma Total de imagenes en subdirs:',sum(dircount))

leyendo imagenes de  C:\Users\Laura Valbuena\Documents\Proyecto\M1000-IA--LLA-\datos\
1/1 [==============================] - 0s 59ms/step
Validando: 1.bmp -> Prediccion: 1
C:\Users\Laura Valbuena\Documents\Proyecto\M1000-IA--LLA-\datos\Val\validation_data 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 10.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 100.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1000.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 1001.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 1002.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1003.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 1004.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 1005.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1006.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1007.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1008.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 1009.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 101.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1010.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1011.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1012.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 1013.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 1014.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1015.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 1016.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1017.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1018.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1019.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 102.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 1020.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1021.bmp -> Prediccion: 1
1/1 [==============================] - 0s 60ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)
C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1022.bmp -> Prediccion: 1
1/1 [==============================] - 0s 58ms/step
Validando: 1023.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1024.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1025.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 1026.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1027.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1028.bmp -> Prediccion: 0
1/1 [==============================] - 0s 59ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1029.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 103.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1030.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 1031.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1032.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1033.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1034.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 1035.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1036.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1037.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1038.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1039.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 104.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 1040.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1041.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1042.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 1043.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1044.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 1045.bmp -> Prediccion: 1
1/1 [==============================] - 0s 58ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1046.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1047.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1048.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1049.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 105.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1050.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1051.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1052.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1053.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1054.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1055.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1056.bmp -> Prediccion: 1
1/1 [==============================] - 0s 62ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)
C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1057.bmp -> Prediccion: 1
1/1 [==============================] - 0s 58ms/step
Validando: 1058.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1059.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 106.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 56ms/step
Validando: 1060.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1061.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1062.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 1063.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1064.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1065.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1066.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 1067.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 1068.bmp -> Prediccion: 1
1/1 [==============================] - 0s 53ms/step
Validando: 1069.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)
C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 107.bmp -> Prediccion: 0
1/1 [==============================] - 0s 61ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1070.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1071.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1072.bmp -> Prediccion: 1
1/1 [==============================] - 0s 58ms/step
Validando: 1073.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)
C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1074.bmp -> Prediccion: 1
1/1 [==============================] - 0s 57ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1075.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1076.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1077.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1078.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1079.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 108.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1080.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1081.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1082.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1083.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1084.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1085.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 55ms/step
Validando: 1086.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1087.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1088.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1089.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 109.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1090.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1091.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1092.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1093.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1094.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1095.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 1096.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 56ms/step
Validando: 1097.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1098.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 1099.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 11.bmp -> Prediccion: 1
1/1 [==============================] - 0s 59ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 110.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1100.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1101.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1102.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1103.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1104.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 1105.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1106.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1107.bmp -> Prediccion: 1
1/1 [==============================] - 0s 58ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)
C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1108.bmp -> Prediccion: 1
1/1 [==============================] - 0s 61ms/step
Validando: 1109.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 111.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1110.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1111.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1112.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1113.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1114.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1115.bmp -> Prediccion: 1
1/1 [==============================] - 0s 55ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1116.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1117.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1118.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1119.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 112.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1120.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1121.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1122.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1123.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1124.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1125.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1126.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1127.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1128.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1129.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 113.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1130.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 1131.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 1132.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1133.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1134.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1135.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1136.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 1137.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1138.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1139.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 114.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1140.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1141.bmp -> Prediccion: 1
1/1 [==============================] - 0s 58ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1142.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1143.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1144.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1145.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1146.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1147.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1148.bmp -> Prediccion: 1
1/1 [==============================] - 0s 59ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)
C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1149.bmp -> Prediccion: 1
1/1 [==============================] - 0s 57ms/step
Validando: 115.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 80ms/step
Validando: 1150.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1151.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 81ms/step
Validando: 1152.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1153.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 74ms/step
Validando: 1154.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 74ms/step
Validando: 1155.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1156.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 1157.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 1158.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 1159.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 116.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 92ms/step
Validando: 1160.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 96ms/step
Validando: 1161.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 78ms/step
Validando: 1162.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1163.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 80ms/step
Validando: 1164.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 1165.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 78ms/step
Validando: 1166.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1167.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1168.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1169.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 117.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1170.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 82ms/step
Validando: 1171.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 1172.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 89ms/step
Validando: 1173.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 84ms/step
Validando: 1174.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 82ms/step
Validando: 1175.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 85ms/step
Validando: 1176.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 1177.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 1178.bmp -> Prediccion: 1
1/1 [==============================] - 0s 58ms/step
Validando: 1179.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)
C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 118.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1180.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1181.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 83ms/step
Validando: 1182.bmp -> Prediccion: 1
1/1 [==============================] - 0s 62ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1183.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1184.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1185.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1186.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1187.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1188.bmp -> Prediccion: 1
1/1 [==============================] - 0s 56ms/step
Validando: 1189.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)
C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 119.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1190.bmp -> Prediccion: 1
1/1 [==============================] - 0s 63ms/step
Validando: 1191.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)
C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1192.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1193.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 56ms/step
Validando: 1194.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1195.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1196.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1197.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1198.bmp -> Prediccion: 1
1/1 [==============================] - 0s 56ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)
C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1199.bmp -> Prediccion: 1
1/1 [==============================] - 0s 67ms/step
Validando: 12.bmp -> Prediccion: 1
1/1 [==============================] - 0s 57ms/step
Validando: 120.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)
C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1200.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1201.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1202.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1203.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1204.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1205.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1206.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1207.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1208.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 87ms/step
Validando: 1209.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 82ms/step
Validando: 121.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 56ms/step
Validando: 1210.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1211.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1212.bmp -> Prediccion: 1
1/1 [==============================] - 0s 62ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1213.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1214.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1215.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1216.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1217.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1218.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1219.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 122.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 1220.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1221.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 94ms/step
Validando: 1222.bmp -> Prediccion: 1
1/1 [==============================] - 0s 56ms/step
Validando: 1223.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)
C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1224.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1225.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1226.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1227.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1228.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1229.bmp -> Prediccion: 1
1/1 [==============================] - 0s 62ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 123.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 1230.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1231.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1232.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1233.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1234.bmp -> Prediccion: 1
1/1 [==============================] - 0s 60ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)
C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1235.bmp -> Prediccion: 1
1/1 [==============================] - 0s 59ms/step
Validando: 1236.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 78ms/step
Validando: 1237.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1238.bmp -> Prediccion: 1
1/1 [==============================] - 0s 55ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)
C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1239.bmp -> Prediccion: 1
1/1 [==============================] - 0s 57ms/step
Validando: 124.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1240.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1241.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1242.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1243.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1244.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1245.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1246.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1247.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1248.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1249.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 125.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1250.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1251.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1252.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1253.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 56ms/step
Validando: 1254.bmp -> Prediccion: 1
1/1 [==============================] - 0s 63ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1255.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 1256.bmp -> Prediccion: 1
1/1 [==============================] - 0s 58ms/step
Validando: 1257.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)
C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1258.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1259.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 126.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1260.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1261.bmp -> Prediccion: 1
1/1 [==============================] - 0s 54ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1262.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 56ms/step
Validando: 1263.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1264.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1265.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1266.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1267.bmp -> Prediccion: 1
1/1 [==============================] - 0s 57ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1268.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1269.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 127.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1270.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1271.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1272.bmp -> Prediccion: 1
1/1 [==============================] - 0s 56ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1273.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1274.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1275.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1276.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1277.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1278.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1279.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 128.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1280.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 1281.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1282.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1283.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1284.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1285.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1286.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 1287.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1288.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1289.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 129.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1290.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1291.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 56ms/step
Validando: 1292.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1293.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1294.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1295.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1296.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1297.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1298.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1299.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 13.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 130.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1300.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1301.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1302.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1303.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1304.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1305.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1306.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 56ms/step
Validando: 1307.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1308.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1309.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 131.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1310.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1311.bmp -> Prediccion: 1
1/1 [==============================] - 0s 60ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1312.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1313.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 56ms/step
Validando: 1314.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 56ms/step
Validando: 1315.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1316.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1317.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1318.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1319.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 132.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 1320.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1321.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1322.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1323.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1324.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1325.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1326.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1327.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1328.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1329.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 133.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1330.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 1331.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1332.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1333.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1334.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1335.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1336.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1337.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1338.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1339.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 134.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1340.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1341.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1342.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1343.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1344.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1345.bmp -> Prediccion: 1
1/1 [==============================] - 0s 59ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1346.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1347.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 96ms/step
Validando: 1348.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 1349.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 135.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 82ms/step
Validando: 1350.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 82ms/step
Validando: 1351.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 1352.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 90ms/step
Validando: 1353.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 80ms/step
Validando: 1354.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 1355.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 1356.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 1357.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 1358.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1359.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 85ms/step
Validando: 136.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1360.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 1361.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 1362.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 91ms/step
Validando: 1363.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 1364.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 87ms/step
Validando: 1365.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 118ms/step
Validando: 1366.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1367.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1368.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1369.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 74ms/step
Validando: 137.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 1370.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 97ms/step
Validando: 1371.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 113ms/step
Validando: 1372.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 1373.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 92ms/step
Validando: 1374.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 78ms/step
Validando: 1375.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 1376.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1377.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1378.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 103ms/step
Validando: 1379.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 89ms/step
Validando: 138.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 1380.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 1381.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 1382.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 1383.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 85ms/step
Validando: 1384.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1385.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 97ms/step
Validando: 1386.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 1387.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 1388.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1389.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 139.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1390.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 83ms/step
Validando: 1391.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 1392.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1393.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 82ms/step
Validando: 1394.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 1395.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1396.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1397.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 82ms/step
Validando: 1398.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1399.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 81ms/step
Validando: 14.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 140.bmp -> Prediccion: 0
1/1 [==============================] - 0s 57ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1400.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1401.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 1402.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 83ms/step
Validando: 1403.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1404.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1405.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 74ms/step
Validando: 1406.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1407.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1408.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 80ms/step
Validando: 1409.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 86ms/step
Validando: 141.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 1410.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1411.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 1412.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1413.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1414.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 102ms/step
Validando: 1415.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1416.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1417.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 87ms/step
Validando: 1418.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 89ms/step
Validando: 1419.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 142.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 80ms/step
Validando: 1420.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1421.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1422.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1423.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1424.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1425.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 85ms/step
Validando: 1426.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 1427.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1428.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1429.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 143.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 1430.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 86ms/step
Validando: 1431.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 1432.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1433.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1434.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 1435.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1436.bmp -> Prediccion: 1
1/1 [==============================] - 0s 62ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1437.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1438.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1439.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 144.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 96ms/step
Validando: 1440.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 113ms/step
Validando: 1441.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 85ms/step
Validando: 1442.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 1443.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 91ms/step
Validando: 1444.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 96ms/step
Validando: 1445.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1446.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1447.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1448.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1449.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 145.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1450.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1451.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1452.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1453.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1454.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 1455.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1456.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1457.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 1458.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1459.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 146.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 55ms/step
Validando: 1460.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 1461.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 1462.bmp -> Prediccion: 1
1/1 [==============================] - 0s 56ms/step
Validando: 1463.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)
C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 56ms/step
Validando: 1464.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1465.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1466.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1467.bmp -> Prediccion: 1
1/1 [==============================] - 0s 59ms/step
Validando: 1468.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)
C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1469.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 147.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1470.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1471.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1472.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1473.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1474.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1475.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1476.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1477.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1478.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1479.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 54ms/step
Validando: 148.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1480.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1481.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1482.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1483.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1484.bmp -> Prediccion: 1
1/1 [==============================] - 0s 58ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1485.bmp -> Prediccion: 1
1/1 [==============================] - 0s 57ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1486.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1487.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 55ms/step
Validando: 1488.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1489.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 149.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 56ms/step
Validando: 1490.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1491.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1492.bmp -> Prediccion: 1
1/1 [==============================] - 0s 59ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)
C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1493.bmp -> Prediccion: 1
1/1 [==============================] - 0s 68ms/step
Validando: 1494.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1495.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1496.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1497.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1498.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1499.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 15.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 150.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 1500.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 1501.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1502.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1503.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 56ms/step
Validando: 1504.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 84ms/step
Validando: 1505.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1506.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1507.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 1508.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1509.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 151.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1510.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 56ms/step
Validando: 1511.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1512.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 56ms/step
Validando: 1513.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1514.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1515.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1516.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1517.bmp -> Prediccion: 1
1/1 [==============================] - 0s 57ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1518.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1519.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 55ms/step
Validando: 152.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1520.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1521.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 1522.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1523.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1524.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 80ms/step
Validando: 1525.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 86ms/step
Validando: 1526.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1527.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1528.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1529.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 153.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1530.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1531.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1532.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1533.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 1534.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1535.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1536.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1537.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1538.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1539.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 154.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1540.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1541.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1542.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 1543.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1544.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1545.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1546.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 78ms/step
Validando: 1547.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1548.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1549.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 155.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1550.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1551.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1552.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1553.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1554.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1555.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1556.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1557.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1558.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1559.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 156.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1560.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1561.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1562.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1563.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1564.bmp -> Prediccion: 1
1/1 [==============================] - 0s 64ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1565.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 1566.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1567.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1568.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1569.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 157.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 81ms/step
Validando: 1570.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1571.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1572.bmp -> Prediccion: 1
1/1 [==============================] - 0s 62ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1573.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 1574.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1575.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1576.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1577.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 1578.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1579.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 158.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1580.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1581.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1582.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 84ms/step
Validando: 1583.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 87ms/step
Validando: 1584.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1585.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1586.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1587.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1588.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1589.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 82ms/step
Validando: 159.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1590.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1591.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1592.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1593.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1594.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 1595.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1596.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1597.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1598.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1599.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 16.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 160.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1600.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 1601.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1602.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1603.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1604.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 81ms/step
Validando: 1605.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1606.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 1607.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 1608.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1609.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 81ms/step
Validando: 161.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1610.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1611.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 1612.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 1613.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 87ms/step
Validando: 1614.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 78ms/step
Validando: 1615.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 1616.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1617.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 86ms/step
Validando: 1618.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1619.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 162.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1620.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1621.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 90ms/step
Validando: 1622.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 1623.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1624.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 87ms/step
Validando: 1625.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1626.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1627.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1628.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 74ms/step
Validando: 1629.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 80ms/step
Validando: 163.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 89ms/step
Validando: 1630.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 86ms/step
Validando: 1631.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 1632.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1633.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1634.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 1635.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 87ms/step
Validando: 1636.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 1637.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 1638.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 1639.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 164.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 74ms/step
Validando: 1640.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1641.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 74ms/step
Validando: 1642.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1643.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1644.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 1645.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1646.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1647.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 1648.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 1649.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 165.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1650.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 1651.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1652.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1653.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 1654.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 109ms/step
Validando: 1655.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 82ms/step
Validando: 1656.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 1657.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 1658.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1659.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 166.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1660.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1661.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1662.bmp -> Prediccion: 1
1/1 [==============================] - 0s 61ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 1663.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1664.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 78ms/step
Validando: 1665.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1666.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1667.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 1668.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 1669.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 167.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1670.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1671.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1672.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1673.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1674.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1675.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 89ms/step
Validando: 1676.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 78ms/step
Validando: 1677.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 1678.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 100ms/step
Validando: 1679.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 81ms/step
Validando: 168.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 1680.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 89ms/step
Validando: 1681.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 81ms/step
Validando: 1682.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1683.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1684.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1685.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1686.bmp -> Prediccion: 1
1/1 [==============================] - 0s 59ms/step
Validando: 1687.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)
C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 56ms/step
Validando: 1688.bmp -> Prediccion: 1
1/1 [==============================] - 0s 60ms/step
Validando: 1689.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)
C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 169.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1690.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 1691.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1692.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1693.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1694.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1695.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 109ms/step
Validando: 1696.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 1697.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 1698.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 1699.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 17.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 109ms/step
Validando: 170.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 80ms/step
Validando: 1700.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 105ms/step
Validando: 1701.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 138ms/step
Validando: 1702.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 78ms/step
Validando: 1703.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 1704.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 101ms/step
Validando: 1705.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 84ms/step
Validando: 1706.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 93ms/step
Validando: 1707.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 86ms/step
Validando: 1708.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 1709.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 86ms/step
Validando: 171.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 88ms/step
Validando: 1710.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 116ms/step
Validando: 1711.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 78ms/step
Validando: 1712.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 86ms/step
Validando: 1713.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 99ms/step
Validando: 1714.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 82ms/step
Validando: 1715.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1716.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 1717.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 83ms/step
Validando: 1718.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 92ms/step
Validando: 1719.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 93ms/step
Validando: 172.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 97ms/step
Validando: 1720.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1721.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1722.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1723.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 89ms/step
Validando: 1724.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 83ms/step
Validando: 1725.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 1726.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1727.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1728.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1729.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 173.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 84ms/step
Validando: 1730.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1731.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1732.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 101ms/step
Validando: 1733.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1734.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1735.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 1736.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1737.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1738.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 92ms/step
Validando: 1739.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 174.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1740.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1741.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 85ms/step
Validando: 1742.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1743.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1744.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 1745.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1746.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1747.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1748.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 1749.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 175.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1750.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1751.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 1752.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1753.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1754.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1755.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1756.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1757.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1758.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1759.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 83ms/step
Validando: 176.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1760.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1761.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1762.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1763.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1764.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1765.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 80ms/step
Validando: 1766.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1767.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1768.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1769.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 177.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1770.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1771.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 80ms/step
Validando: 1772.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1773.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 1774.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1775.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 89ms/step
Validando: 1776.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1777.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1778.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1779.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 178.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1780.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1781.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1782.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1783.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1784.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1785.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1786.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1787.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1788.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1789.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 179.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 1790.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1791.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 55ms/step
Validando: 1792.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1793.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1794.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1795.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1796.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1797.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1798.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 74ms/step
Validando: 1799.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 18.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 56ms/step
Validando: 180.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1800.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1801.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1802.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 1803.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 1804.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1805.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1806.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1807.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 83ms/step
Validando: 1808.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 55ms/step
Validando: 1809.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 87ms/step
Validando: 181.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 1810.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 1811.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 81ms/step
Validando: 1812.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1813.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 80ms/step
Validando: 1814.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 1815.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1816.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1817.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1818.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1819.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 182.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 56ms/step
Validando: 1820.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1821.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1822.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1823.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1824.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1825.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1826.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1827.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1828.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1829.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 183.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1830.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 84ms/step
Validando: 1831.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1832.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1833.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1834.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1835.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 1836.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1837.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1838.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 85ms/step
Validando: 1839.bmp -> Prediccion: 0
1/1 [==============================] - 0s 56ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 184.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 1840.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1841.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1842.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 1843.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 1844.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1845.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 1846.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 82ms/step
Validando: 1847.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1848.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 86ms/step
Validando: 1849.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 185.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 1850.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 1851.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1852.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1853.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 55ms/step
Validando: 1854.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 1855.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1856.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 74ms/step
Validando: 1857.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 1858.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1859.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 186.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 1860.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 1861.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 1862.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 1863.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1864.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 1865.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 55ms/step
Validando: 1866.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 1867.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 187.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 188.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 97ms/step
Validando: 189.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 19.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 190.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 191.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 192.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 193.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 194.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 74ms/step
Validando: 195.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 196.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 197.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 198.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 199.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 2.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 20.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 200.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 201.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 202.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 203.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 204.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 205.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 206.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 207.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 208.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 209.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 21.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 210.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 74ms/step
Validando: 211.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 212.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 213.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 214.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 215.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 216.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 217.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 218.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 219.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 22.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 80ms/step
Validando: 220.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 221.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 222.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 223.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 224.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 225.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 226.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 227.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 228.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 229.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 23.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 230.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 231.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 232.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 233.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 54ms/step
Validando: 234.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 90ms/step
Validando: 235.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 236.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 237.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 238.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 239.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 24.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 240.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 241.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 242.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 86ms/step
Validando: 243.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 244.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 245.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 85ms/step
Validando: 246.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 247.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 248.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 249.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 25.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 250.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 251.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 252.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 253.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 254.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 255.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 256.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 257.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 258.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 259.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 82ms/step
Validando: 26.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 74ms/step
Validando: 260.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 94ms/step
Validando: 261.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 262.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 263.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 264.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 78ms/step
Validando: 265.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 266.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 78ms/step
Validando: 267.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 92ms/step
Validando: 268.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 269.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 27.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 270.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 271.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 272.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 74ms/step
Validando: 273.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 274.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 275.bmp -> Prediccion: 0
1/1 [==============================] - 0s 59ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 276.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 277.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 278.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 279.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 28.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 280.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 83ms/step
Validando: 281.bmp -> Prediccion: 1
1/1 [==============================] - 0s 55ms/step
Validando: 282.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)
C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 283.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 284.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 285.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 286.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 287.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 288.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 289.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 29.bmp -> Prediccion: 1
1/1 [==============================] - 0s 55ms/step
Validando: 290.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)
C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 291.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 292.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 293.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 294.bmp -> Prediccion: 1
1/1 [==============================] - 0s 62ms/step

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

Validando: 295.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 296.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 297.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 298.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 299.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 3.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 30.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 300.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 301.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 96ms/step
Validando: 302.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 81ms/step
Validando: 303.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 304.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 305.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 306.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 307.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 308.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 309.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 31.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 310.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 311.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 90ms/step
Validando: 312.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 74ms/step
Validando: 313.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 314.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 81ms/step
Validando: 315.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 316.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 85ms/step
Validando: 317.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 318.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 85ms/step
Validando: 319.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 32.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 142ms/step
Validando: 320.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 143ms/step
Validando: 321.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 322.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 323.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 78ms/step
Validando: 324.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 325.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 326.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 327.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 328.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 329.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 33.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 330.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 331.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 332.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 333.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 334.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 335.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 100ms/step
Validando: 336.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 337.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 81ms/step
Validando: 338.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 95ms/step
Validando: 339.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 81ms/step
Validando: 34.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 122ms/step
Validando: 340.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 341.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 74ms/step
Validando: 342.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 343.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 92ms/step
Validando: 344.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 90ms/step
Validando: 345.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 346.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 100ms/step
Validando: 347.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 100ms/step
Validando: 348.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 80ms/step
Validando: 349.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 82ms/step
Validando: 35.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 81ms/step
Validando: 350.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 351.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 352.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 353.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 354.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 355.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 356.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 357.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 78ms/step
Validando: 358.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 359.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 36.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 360.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 361.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 362.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 85ms/step
Validando: 363.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 364.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 365.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 366.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 367.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 78ms/step
Validando: 368.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 369.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 37.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 370.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 371.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 372.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 87ms/step
Validando: 373.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 374.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 375.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 111ms/step
Validando: 376.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 78ms/step
Validando: 377.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 378.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 379.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 38.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 380.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 381.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 382.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 383.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 81ms/step
Validando: 384.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 385.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 386.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 387.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 388.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 389.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 39.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 99ms/step
Validando: 390.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 391.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 392.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 393.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 394.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 86ms/step
Validando: 395.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 396.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 397.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 398.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 399.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 4.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 96ms/step
Validando: 40.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 400.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 401.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 402.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 403.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 404.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 405.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 406.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 407.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 408.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 84ms/step
Validando: 409.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 41.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 410.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 411.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 412.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 413.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 96ms/step
Validando: 414.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 78ms/step
Validando: 415.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 416.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 81ms/step
Validando: 417.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 418.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 419.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 42.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 420.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 421.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 422.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 423.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 424.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 425.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 426.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 427.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 74ms/step
Validando: 428.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 429.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 43.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 430.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 87ms/step
Validando: 431.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 432.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 56ms/step
Validando: 433.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 434.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 435.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 436.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 437.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 438.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 98ms/step
Validando: 439.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 44.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 74ms/step
Validando: 440.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 441.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 442.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 443.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 444.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 445.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 446.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 447.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 448.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 449.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 45.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 450.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 451.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 452.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 453.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 454.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 455.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 456.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 457.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 458.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 459.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 46.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 460.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 461.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 462.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 463.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 464.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 465.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 466.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 467.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 468.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 78ms/step
Validando: 469.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 47.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 470.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 471.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 472.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 80ms/step
Validando: 473.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 81ms/step
Validando: 474.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 475.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 476.bmp -> Prediccion: 0
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 477.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 478.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 74ms/step
Validando: 479.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 48.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 86ms/step
Validando: 480.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 481.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 482.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 483.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 484.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 485.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 486.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 487.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 488.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 489.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 49.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 490.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 88ms/step
Validando: 491.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 492.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 493.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 494.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 495.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 496.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 497.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 498.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 499.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 74ms/step
Validando: 5.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 50.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 500.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 501.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 502.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 503.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 504.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 85ms/step
Validando: 505.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 506.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 507.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 508.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 509.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 51.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 510.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 511.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 512.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 513.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 514.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 74ms/step
Validando: 515.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 516.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 517.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 518.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 519.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 52.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 520.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 521.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 74ms/step
Validando: 522.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 88ms/step
Validando: 523.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 524.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 525.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 526.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 527.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 78ms/step
Validando: 528.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 92ms/step
Validando: 529.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 53.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 530.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 531.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 532.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 533.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 534.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 535.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 536.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 537.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 538.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 539.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 84ms/step
Validando: 54.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 540.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 74ms/step
Validando: 541.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 542.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 543.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 544.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 545.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 546.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 547.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 548.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 549.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 55.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 550.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 83ms/step
Validando: 551.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 552.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 106ms/step
Validando: 553.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 554.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 86ms/step
Validando: 555.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 556.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 557.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 558.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 559.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 56.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 560.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 561.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 80ms/step
Validando: 562.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 563.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 90ms/step
Validando: 564.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 565.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 91ms/step
Validando: 566.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 78ms/step
Validando: 567.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 568.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 569.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 85ms/step
Validando: 57.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 570.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 571.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 572.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 573.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 574.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 575.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 576.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 577.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 578.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 124ms/step
Validando: 579.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 58.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 580.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 581.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 582.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 583.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 584.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 585.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 586.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 587.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 588.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 103ms/step
Validando: 589.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 59.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 590.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 591.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 592.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 593.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 594.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 595.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 78ms/step
Validando: 596.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 597.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 598.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 599.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 98ms/step
Validando: 6.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 105ms/step
Validando: 60.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 91ms/step
Validando: 600.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 601.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 86ms/step
Validando: 602.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 603.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 80ms/step
Validando: 604.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 89ms/step
Validando: 605.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 74ms/step
Validando: 606.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 92ms/step
Validando: 607.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 80ms/step
Validando: 608.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 609.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 99ms/step
Validando: 61.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 610.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 81ms/step
Validando: 611.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 612.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 613.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 81ms/step
Validando: 614.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 83ms/step
Validando: 615.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 81ms/step
Validando: 616.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 617.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 618.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 619.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 62.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 620.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 84ms/step
Validando: 621.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 81ms/step
Validando: 622.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 623.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 624.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 625.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 626.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 627.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 628.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 84ms/step
Validando: 629.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 63.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 630.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 631.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 632.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 86ms/step
Validando: 633.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 86ms/step
Validando: 634.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 635.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 636.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 637.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 638.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 639.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 95ms/step
Validando: 64.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 81ms/step
Validando: 640.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 74ms/step
Validando: 641.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 642.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 80ms/step
Validando: 643.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 644.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 645.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 646.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 97ms/step
Validando: 647.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 648.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 649.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 89ms/step
Validando: 65.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 83ms/step
Validando: 650.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 651.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 74ms/step
Validando: 652.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 653.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 654.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 655.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 656.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 657.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 82ms/step
Validando: 658.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 80ms/step
Validando: 659.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 66.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 660.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 91ms/step
Validando: 661.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 86ms/step
Validando: 662.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 663.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 664.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 107ms/step
Validando: 665.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 666.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 80ms/step
Validando: 667.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 668.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 669.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 67.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 670.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 82ms/step
Validando: 671.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 78ms/step
Validando: 672.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 673.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 674.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 675.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 676.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 677.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 678.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 679.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 68.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 680.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 681.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 682.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 683.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 82ms/step
Validando: 684.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 685.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 686.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 687.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 100ms/step
Validando: 688.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 689.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 80ms/step
Validando: 69.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 690.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 691.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 692.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 693.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 694.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 695.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 696.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 697.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 698.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 699.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 7.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 70.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 700.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 701.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 702.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 703.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 704.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 705.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 706.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 707.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 708.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 84ms/step
Validando: 709.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 71.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 710.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 711.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 712.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 713.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 714.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 715.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 716.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 717.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 718.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 719.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 72.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 720.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 721.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 722.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 723.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 724.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 725.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 726.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 727.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 728.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 729.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 73.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 730.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 731.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 732.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 733.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 86ms/step
Validando: 734.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 735.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 736.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 737.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 738.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 55ms/step
Validando: 739.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 74.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 740.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 741.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 742.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 743.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 744.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 745.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 746.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 747.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 748.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 749.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 88ms/step
Validando: 75.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 87ms/step
Validando: 750.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 751.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 81ms/step
Validando: 752.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 753.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 754.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 755.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 756.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 757.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 758.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 759.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 76.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 760.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 761.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 762.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 763.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 764.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 765.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 766.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 767.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 84ms/step
Validando: 768.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 769.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 77.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 770.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 771.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 772.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 80ms/step
Validando: 773.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 774.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 86ms/step
Validando: 775.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 776.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 777.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 778.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 74ms/step
Validando: 779.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 78.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 780.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 781.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 782.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 81ms/step
Validando: 783.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 784.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 785.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 786.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 787.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 788.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 789.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 79.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 790.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 791.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 792.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 793.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 794.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 795.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 796.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 797.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 798.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 799.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 8.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 80.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 800.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 801.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 802.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 803.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 804.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 805.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 806.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 807.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 808.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 809.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 81.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 810.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 811.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 812.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 813.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 814.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 815.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 816.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 817.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 818.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 78ms/step
Validando: 819.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 82.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 820.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 821.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 822.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 823.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 824.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 825.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 826.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 827.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 828.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 829.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 83.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 830.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 831.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 832.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 833.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 834.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 835.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 836.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 837.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 838.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 839.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 96ms/step
Validando: 84.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 840.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 841.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 842.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 843.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 844.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 845.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 846.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 847.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 848.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 56ms/step
Validando: 849.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 85.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 850.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 76ms/step
Validando: 851.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 852.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 853.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 854.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 855.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 856.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 857.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 858.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 859.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 86.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 860.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 861.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 862.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 863.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 864.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 865.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 866.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 867.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 868.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 869.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 87.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 870.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 871.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 872.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 873.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 74ms/step
Validando: 874.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 875.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 876.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 877.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 878.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 879.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 88.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 880.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 881.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 58ms/step
Validando: 882.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 883.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 884.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 885.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 886.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 887.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 888.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 889.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 89.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 80ms/step
Validando: 890.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 891.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 892.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 893.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 81ms/step
Validando: 894.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 88ms/step
Validando: 895.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 896.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 897.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 898.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 899.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 9.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 90.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 900.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 901.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 902.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 903.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 904.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 905.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 81ms/step
Validando: 906.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 907.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 71ms/step
Validando: 908.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 909.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 91.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 74ms/step
Validando: 910.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 911.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 912.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 913.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 914.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 915.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 916.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 917.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 918.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 919.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 92.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 920.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 921.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 922.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 923.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 924.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 77ms/step
Validando: 925.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 926.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 80ms/step
Validando: 927.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 928.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 72ms/step
Validando: 929.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 84ms/step
Validando: 93.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 75ms/step
Validando: 930.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 98ms/step
Validando: 931.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 932.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 933.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 934.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 935.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 936.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 937.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 938.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 939.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 94.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 940.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 941.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 942.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 943.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 944.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 945.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 946.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 947.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 948.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 57ms/step
Validando: 949.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 95.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 950.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 951.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 952.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 74ms/step
Validando: 953.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 954.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 955.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 956.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 957.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 958.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 959.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 96.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 960.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 961.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 962.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 963.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 964.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 965.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 966.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 967.bmp -> Prediccion: 0

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 968.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 969.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 97.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 59ms/step
Validando: 970.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 971.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 972.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 973.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 68ms/step
Validando: 974.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 975.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 976.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 70ms/step
Validando: 977.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 978.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 67ms/step
Validando: 979.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 98.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 980.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 981.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 982.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 65ms/step
Validando: 983.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 63ms/step
Validando: 984.bmp -> Prediccion: 1
1/1 [==============================] - ETA: 0s

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 985.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 986.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 987.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 988.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 989.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 69ms/step
Validando: 99.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 990.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 991.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 66ms/step
Validando: 992.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 62ms/step
Validando: 993.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 79ms/step
Validando: 994.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 60ms/step
Validando: 995.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 64ms/step
Validando: 996.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 61ms/step
Validando: 997.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 73ms/step
Validando: 998.bmp -> Prediccion: 1

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

1/1 [==============================] - 0s 84ms/step
Validando: 999.bmp -> Prediccion: 1
Directorios leidos: 1
Imagenes en cada directorio [1867]
suma Total de imagenes en subdirs: 1867

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\142001448.py:35: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_predicted = df_predicted.append({'Filename' : filename,'Prediccion' : predict}, ignore_index=True)

In [10]:
df_predicted

      Filename Prediccion
0        1.bmp          1
1       10.bmp          1
2      100.bmp          1
3     1000.bmp          1
4     1001.bmp          1
...        ...        ...
1862   995.bmp          1
1863   996.bmp          1
1864   997.bmp          1
1865   998.bmp          1
1866   999.bmp          1

[1867 rows x 2 columns]

# Validar Predicciones
Se carga el dataframe que contiene el nombre de la imagen y el pronostico correcto para la imagen en la columna labels donde:

* 1 - Malignant

* 0 - Benign

In [11]:
dirname = os.path.join(os.getcwd(), 'datos/Val/validation_data/')
datos = pd.read_csv(dirname +'labels_images.csv',sep=',')
datos

                Patient_ID new_names  labels
0      UID_57_29_1_all.bmp     1.bmp       1
1      UID_57_22_2_all.bmp     2.bmp       1
2      UID_57_31_3_all.bmp     3.bmp       1
3     UID_H49_35_1_hem.bmp     4.bmp       0
4      UID_58_6_13_all.bmp     5.bmp       1
...                    ...       ...     ...
1862   UID_54_33_1_all.bmp  1863.bmp       1
1863   UID_55_24_1_all.bmp  1864.bmp       1
1864  UID_H32_20_1_hem.bmp  1865.bmp       0
1865   UID_54_30_2_all.bmp  1866.bmp       1
1866   UID_66_10_3_all.bmp  1867.bmp       1

[1867 rows x 3 columns]

In [12]:
#Se realiza el Join del dataframe con los resultados correctos y el dataframe con la predicción
df_join = datos.set_index('new_names').join(df_predicted.set_index('Filename')).reset_index()
df_join['Valor'] = None
df_join

     new_names            Patient_ID  labels Prediccion Valor
0        1.bmp   UID_57_29_1_all.bmp       1          1  None
1        2.bmp   UID_57_22_2_all.bmp       1          1  None
2        3.bmp   UID_57_31_3_all.bmp       1          1  None
3        4.bmp  UID_H49_35_1_hem.bmp       0          1  None
4        5.bmp   UID_58_6_13_all.bmp       1          1  None
...        ...                   ...     ...        ...   ...
1862  1863.bmp   UID_54_33_1_all.bmp       1          1  None
1863  1864.bmp   UID_55_24_1_all.bmp       1          1  None
1864  1865.bmp  UID_H32_20_1_hem.bmp       0          1  None
1865  1866.bmp   UID_54_30_2_all.bmp       1          1  None
1866  1867.bmp   UID_66_10_3_all.bmp       1          1  None

[1867 rows x 5 columns]

In [13]:
for i in range(len(df_join)):
    if df_join['labels'][i] == df_join['Prediccion'][i]:
        df_join['Valor'][i] = 'Correct'
    else:
        df_join['Valor'][i] = 'Incorrect'

C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\3056822646.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_join['Valor'][i] = 'Correct'
C:\Users\Laura Valbuena\AppData\Local\Temp\ipykernel_25856\3056822646.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_join['Valor'][i] = 'Incorrect'

In [14]:
df_join

     new_names            Patient_ID  labels Prediccion      Valor
0        1.bmp   UID_57_29_1_all.bmp       1          1    Correct
1        2.bmp   UID_57_22_2_all.bmp       1          1    Correct
2        3.bmp   UID_57_31_3_all.bmp       1          1    Correct
3        4.bmp  UID_H49_35_1_hem.bmp       0          1  Incorrect
4        5.bmp   UID_58_6_13_all.bmp       1          1    Correct
...        ...                   ...     ...        ...        ...
1862  1863.bmp   UID_54_33_1_all.bmp       1          1    Correct
1863  1864.bmp   UID_55_24_1_all.bmp       1          1    Correct
1864  1865.bmp  UID_H32_20_1_hem.bmp       0          1  Incorrect
1865  1866.bmp   UID_54_30_2_all.bmp       1          1    Correct
1866  1867.bmp   UID_66_10_3_all.bmp       1          1    Correct

[1867 rows x 5 columns]

In [15]:
df_join.to_csv('leucemia_Pronostico.csv', index=False, sep=';')

In [16]:
df_join.groupby("Valor", sort=False).describe()

           labels
            count      mean       std  min  25%  50%  75%  max
Valor
Correct    1314.0  0.899543  0.300722  0.0  1.0  1.0  1.0  1.0
Incorrect   553.0  0.066908  0.250088  0.0  0.0  0.0  0.0  1.0

In [17]:
df_join.groupby('Valor').size().reset_index().rename(columns={0:'count'})

       Valor  count
0    Correct   1314
1  Incorrect    553

De el total de las imagenes (1867), el 89.9% tuvo una predicción correcta correspondiete a 1314 imagenes